name: Enov8 CMDB Update

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-cmdb:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Remove this if not needed
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enov8 - Deployment Version Update
        uses: enov8-Ltd/enov8-update-deployment-version@v1.0.0
        with:
          enov8_url: ${{ secrets.ENOV8_BASE_URL }}
          app_id: ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}
          resourceType: "Environment Instance"
          resourceName: "GDW (DEV)"
          version: "18.99"
          status: "InOperation"
          # ✅ Required for MicroService
          systemInstance: ""
         
