name: Enov8 CMDB Update

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  update-cmdb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run your action
        uses: hpashok24/enov8-cmdb-update@main
        with:
          enov8_url: https://enov8-india.enov8.com/ecosystem/api/SystemInstance
          app_id: ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}
          resourceType: SystemInstance
          resourceName: GDW (Prod)
