name: Enov8 CMDB Update

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-cmdb:
    runs-on: ubuntu-latest

    steps:
      # Remove this if not needed
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enov8 - CMDB Update
        uses: hpashok24/enov8-cmdb-update@v2.0.1
        with:
          enov8_url: ${{ secrets.ENOV8_BASE_URL }}
          app_id: ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}
          resourceType: "Environment Instance"
          resourceName: "GDW (DEV)"
          includeVersion: true
          version: "18.0.10"
          includeStatus: true
          status: "UnplannedOutage"
