name: Send Enov8 Update
on:
  workflow_dispatch:

jobs:
  notify-enov8:
    runs-on: ubuntu-latest
    steps:
      - name: Update CMDB in Enov8
        uses: hpashok24/enov8-cmdb-update@main
        with:
          resourceType: "Environment Instance"
          resourceName: "GDW (DEV)"
          includeVersion: "true"
          version: "18.0.100"
          includeStatus: "false"
          status: "InOperation"
          app_id:  ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}
          enov8_url: ${{ secrets.ENOV8_BASE_URL }}
