name: Enov8 CMDB Update

on:
  workflow_dispatch:

jobs:
  update-cmdb:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Enov8 - Deployment Version Update
        uses: hpashok24/enov8-cmdb-update@main
        with:
          enov8_url: ${{ secrets.ENOV8_BASE_URL }}
          app_id: ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}

          resourceType: "Environment Instance"
          resourceName: "GDW (SIT30)"

          version: "18.0.15"
          autocreate: "true"

          metadata: |
            {
              "Status": "InOperation",
              "System": "GDW",
              "Environment": "SIT Env"
            }
